# Language setting http://docs.shippable.com/ci/languages/node/
language: node_js

# use this to control what branches get built.
# http://docs.shippable.com/ci/advancedOptions/branches/
branches:
  only:
    - master

# using pre-defined build variables
# full list http://docs.shippable.com/ci/advancedOptions/environmentVariables/
env:
  global:
    - TEST_RESULTS_DIR=$SHIPPABLE_REPO_DIR/shippable/testresults
    - CODE_COVERAGE_DIR=$SHIPPABLE_REPO_DIR/shippable/codecoverage
    - TESTS_LOC_DIR=$SHIPPABLE_REPO_DIR/tests
    - MOD_LOC=$SHIPPABLE_REPO_DIR/node_modules/.bin/
    - ECR_REPO=679404489841.dkr.ecr.us-east-1.amazonaws.com/deploy-ecs-lb

build:

  # http://docs.shippable.com/ci/shippableyml/#ci
  ci:
    # npm mirrors can sometimes be flacky, better to use shippable_retry
    # http://docs.shippable.com/ci/advancedOptions/retry/
    - shippable_retry npm install
    - mkdir -p $TEST_RESULTS_DIR && mkdir -p $CODE_COVERAGE_DIR
    - pushd $TESTS_LOC_DIR
    - $MOD_LOC/mocha --recursive "$TESTS_LOC_DIR/**/*.spec.js" -R mocha-junit-reporter --reporter-options mochaFile=$TEST_RESULTS_DIR/testresults.xml
    - $MOD_LOC/istanbul --include-all-sources cover -root "$SHIPPABLE_REPO_DIR/routes" $SHIPPABLE_REPO_DIR/node_modules/mocha/bin/_mocha -- -R spec-xunit-file --recursive "$TESTS_LOC_DIR/**/*.spec.js"
    - $MOD_LOC/istanbul report cobertura --dir $CODE_COVERAGE_DIR
    - popd

  # http://docs.shippable.com/ci/shippableyml/#post_ci
  post_ci:
    - 'if [ $IS_PULL_REQUEST == "false" ] ; then docker build -t $ECR_REPO:$BRANCH.$BUILD_NUMBER .; fi'
    - 'if [ $IS_PULL_REQUEST == "false" ] ; then docker push $ECR_REPO:$BRANCH.$BUILD_NUMBER ; fi'
    - 'if [ $IS_PULL_REQUEST == "false" ] ; then echo "versionName=$BRANCH.$BUILD_NUMBER" > $JOB_STATE/deploy-ecs-lb-image.env ; fi'

# Integrations are used to connect external resources to CI
# http://docs.shippable.com/integrations/overview/
integrations:
  # adding awsKeys integration so that credentials are available to CI Job
  # http://docs.shippable.com/platform/integration/aws-keys/
  hub:
    - integrationName: dr-aws-keys
      type: amazonKeys

resources:
  - name: deploy-ecs-lb-image
    type: image
    flags:
      - deploy-ecs-lb
    integration: dr-aws-keys
    pointer:
      sourceName: "679404489841.dkr.ecr.us-east-1.amazonaws.com/deploy-ecs-lb"
    seed:
      versionName: "latest"

  - name: deploy-ecs-lb-docker-options
    type: dockerOptions
    flags:
      - deploy-ecs-lb
    version:
      memory: 100
      portMappings:
        - 0:80

  - name: deploy-ecs-lb-elb
    type: loadBalancer
    flags:
      - deploy-ecs-lb
    pointer:
      sourceName: deploy-ecs-elb
      method: classic
      role: role-for-ecs-lb

  - name: deploy-ecs-lb-alb
    type: loadBalancer
    flags:
      - deploy-ecs-lb
    pointer:
      sourceName: arn:aws:elasticloadbalancing:us-east-1:679404489841:targetgroup/ecs-deploy-alb-tgtgrp/394643319fd6a729
      method: application
      role: role-for-ecs-lb


  - name: deploy-ecs-lb-params
    type: params
    flags:
      - deploy-ecs-lb
    version:
      params:
        PORT: 80
        ENVIRONMENT: "lb_test"

  - name: deploy-ecs-lb-replicas
    type: replicas
    flags:
      - deploy-ecs-lb
    version:
      count: 3

  - name: deploy-ecs-lb-ecs-cluster
    type: cluster
    flags:
      - deploy-ecs-lb
    integration: dr-aws-keys
    pointer:
      sourceName : "deploy-ecs-basic" #name of the cluster to which we are deploying
      region: "us-east-1"


jobs:
  - name: deploy-ecs-lb_runCI
    type: runCI
    flags:
      - deploy-ecs-lb
    steps:
      - OUT: deploy-ecs-lb-image

  - name: deploy-ecs-lb-manifest
    type: manifest
    flags:
      - deploy-ecs-lb
    steps:
     - IN: deploy-ecs-lb-image
     - IN: deploy-ecs-lb-docker-options
     - IN: deploy-ecs-lb-params
     - IN: deploy-ecs-lb-replicas

  - name: deploy-ecs-lb-deploy
    type: deploy
    method: upgrade
    flags:
      - deploy-ecs-lb
    steps:
      - IN: deploy-ecs-lb-replicas
      - IN: deploy-ecs-lb-manifest
      - IN: deploy-ecs-lb-ecs-cluster
      - IN: deploy-ecs-lb-alb
        applyTo:
          - manifest: deploy-ecs-lb-manifest
            image: deploy-ecs-lb-image
            port: 80
